### ISSUE TITLE
User Preference

### ISSUE THREAD

**Issue by KhaledGad** [RAMP-project/RAMP#90]
When using User Preference for example in the example of cooking appliance, the expected results should be between [Appliance1 or Appliance 2] for user_2 who has 2 preferences.

however, when you run the example you can get randomisation that are [0, Appliance1, Appliance2, Appliance1 + Appliance2]

And this is due to the fact that rand_daily_prof would coincide with user_preference for each appliance in the user.

Example if we ran it for hypothetically 4 days
rand_daily_prof
1
2
  this is a App1+App2
2
1
    this is a zero
1
1
 this is only App1
2
2
 this is only App2

**Comment by FLomb** [comment]
Hi @KhaledGad, thanks for opening this issue. I see what you mean. I think this is indeed a bug introduced by our restructuring of the code for v0.4.0. The code still does the right thing with the randomisation of the daily user preference, checking it against the preference index of a given appliance. Except, it now does it anew for each appliance, instead of doing it once per day and for all appliances, as it was before. This means that for each appliance the number is re-calculated, which is not what we want.

@Bachibouzouk, what is the most elegant way to solve this, in your opinion? I think we should somehow move it to the top of the `User` class.

**Comment by Bachibouzouk** [comment]
Hello @KhaledGad  and @FLomb, I proposed a fix in #92, let me know if this addresses the problem

**Comment by KhaledGad** [comment]
For the example of how it should result in, is this one [https://rampdemand.readthedocs.io/en/latest/examples/cooking_app/cooking_app.html](url)

For the edits, i would say now it is working properly for user_preference = 2 , in sense that he chooses one of them.

but when i tried more than 2, for example 3

when he randomise and get 3, you turn on the device with 2 as well. it is acting as if 1s turn on switch 1, and any other turn on switch 2, and doesn't see the rest of the appliance

"https://github.com/KhaledGad/Edits/blob/38fb40d30d413a96f1fbd332e56f4f09552d2b87/Cooking%20appliances.py"

**Comment by Bachibouzouk** [comment]
@KhaledGad I am sorry to inform you that the example you inspired yourself with was unfortunately missed when we updated the code as I see `Year_behavior` is one of the argument of the method `generate_single_load_profile` which is wrong. You actually corrected it in your code snippet by using `day_type` instead. unfortunately you passed it `year_behaviour` as a value instead of `year_behaviour[day]` 

I printed out the appliance pref_index as well of the user random daily preference, as you can see, only the appliance with the correct preference is turned on each day. Can you let us know if it satisfies you? Thanks again for your time and patience, it is really a great contribution and will help make the code better
```
Day number:  0
consider appliance
soup for lunch 	appliance pref_index:  1 	user random daily preference 1
Day number:  0
skip appliance
rice for lunch 	appliance pref_index:  2 	user random daily preference 1
Day number:  0
skip appliance
rice for lunch 	appliance pref_index:  3 	user random daily preference 1
Day number:  1
skip appliance
soup for lunch 	appliance pref_index:  1 	user random daily preference 2
Day number:  1
consider appliance
rice for lunch 	appliance pref_index:  2 	user random daily preference 2
Day number:  1
skip appliance
rice for lunch 	appliance pref_index:  3 	user random daily preference 2
Day number:  2
skip appliance
soup for lunch 	appliance pref_index:  1 	user random daily preference 3
Day number:  2
skip appliance
rice for lunch 	appliance pref_index:  2 	user random daily preference 3
Day number:  2
consider appliance
rice for lunch 	appliance pref_index:  3 	user random daily preference 3
Day number:  3
skip appliance
soup for lunch 	appliance pref_index:  1 	user random daily preference 3
Day number:  3
skip appliance
rice for lunch 	appliance pref_index:  2 	user random daily preference 3
Day number:  3
consider appliance
rice for lunch 	appliance pref_index:  3 	user random daily preference 3
Day number:  4
consider appliance
soup for lunch 	appliance pref_index:  1 	user random daily preference 1
Day number:  4
skip appliance
rice for lunch 	appliance pref_index:  2 	user random daily preference 1
Day number:  4
skip appliance
rice for lunch 	appliance pref_index:  3 	user random daily preference 1
Day number:  5
skip appliance
soup for lunch 	appliance pref_index:  1 	user random daily preference 3
Day number:  5
skip appliance
rice for lunch 	appliance pref_index:  2 	user random daily preference 3
Day number:  5
consider appliance
rice for lunch 	appliance pref_index:  3 	user random daily preference 3
Day number:  6
skip appliance
soup for lunch 	appliance pref_index:  1 	user random daily preference 2
Day number:  6
consider appliance
rice for lunch 	appliance pref_index:  2 	user random daily preference 2
Day number:  6
skip appliance
rice for lunch 	appliance pref_index:  3 	user random daily preference 2
Day number:  7
consider appliance
soup for lunch 	appliance pref_index:  1 	user random daily preference 1
Day number:  7
skip appliance
rice for lunch 	appliance pref_index:  2 	user random daily preference 1
Day number:  7
skip appliance
rice for lunch 	appliance pref_index:  3 	user random daily preference 1

```

**Comment by KhaledGad** [comment]
Thank you for you help! 

I edited the day_type function, but i still have the same problem with the results. so with having 3 preferences as in the example i showed you

this is the rand_pref per day (10days)
1
2
3
1
1
2
2
1
3
3

![image](https://github.com/RAMP-project/RAMP/assets/82186176/0add69b2-73c6-4275-bac4-5c6bd107fcab)

however, when doing it with 2,

2
1
1
2
1
1
1
2
1
2

![image](https://github.com/RAMP-project/RAMP/assets/82186176/a69975b7-ad2d-40e2-ba2f-1492b7b89527)

Notice in two graphs, the max and minimum are the same while in the 3rd appliance i put a higher value than both the others.

when he randomise and get 3, you turn on the device with 2 as well. it is acting as if 1s turn on switch 1, and any other turn on switch 2, and doesn't see the rest of the appliance.

`# # new meal
new_meal = user_2.add_appliance(
    name = "rice for lunch",
    power = 5000,
    func_time = 15,
    func_cycle = 15,
    # thermal_p_var = 0.2,
    pref_index = 3,  # the second preference
    fixed_cycle = 1,
    window_1 = [12*60,15*60],
    p_11 = 1200,   # power of the first cycle
    t_11 = 5,      # time needed for the first cycle
    p_12 = 600,    # power of the second cycle
    t_12 = 10,     # time needed for the second cycle
    cw11 = [12*60,15*60]

)`

**Comment by Bachibouzouk** [comment]
@KhaledGad - I checked and the fact that you don't see difference between preferences can be explained by the fact that you have 1 duty cycle enabled for all appliances with exactly the same parameters, if you change the duty cycle p_11 and p_12 to different values for different appliances you will see the changes in the profile. If you don't need duty cycle but merely a constant power you can also comment out `fixed_cycle` as well as `p_11, p_12, t_11, t_12, cw11`

**Comment by FLomb** [comment]
Hi @KhaledGad, I agree with @Bachibouzouk. The issue you have now is that, as soon as you specify a `fixed_cycle`, this overrides the `power` parameter. The power consumption will be, in fact, dictated by the parameters `p_11` and `p_12` that you have specified for your cycle, which do not change across the 3 appliances you have in your input file. 

So, even when appliance 3 is correctly selected to match a preference index of 3, the behaviour of the appliance is identical to that of the others, preventing you from seeing it. If you change the `fixed_cycle` of your different appliances, you'll notice such differences.

Can you confirm so that we can consider this issue closed and fixed by PR #92 ?

**Comment by KhaledGad** [comment]
Yes, true! now it is functioning as it should, thank you!

**Comment by KhaledGad** [comment]
Yes, true! now it is functioning as it should, thank you!
